version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "shun10114@gmail.com"
            git config --global user.name "Seolhun"
            echo "machine github.com login Seolhun password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=<GIT_USER> yarn run publish-gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
